### ISSUE TITLE
empty home page

### ISSUE THREAD

**Issue by joyously** [elmsln/haxtheweb.org#1]
The home page is empty.

![haxtheweb org-home](https://user-images.githubusercontent.com/7957680/62839554-0ee87900-bc51-11e9-8f51-dd8e744bb24d.png)

**Comment by btopro** [comment]
So this will seem odd but this screenshot basically blew my entire day. It is solved to the current level of my best abilities. Meaning if you go back to haxtheweb.org (might need to clear cache, not sure) and refresh, you should see the site that the vast majority of browsing traffic is seeing.

This watered down design was only supposed to be delivered to Edge. The authoring tools don't load correctly still and the video player tag locks up Firefox 52 / Seamonkeys, but loads faster than it did previously (as do many other assets, type issue). While still not loading the editor into ES5 compiled browsers (which is what this is being delivered, an ES5 version of the assets), it should provide a more accurate experience then it did previously throughout some of your issues posted.

I'm going to port this integration routine to the wp and other plugins we support as the way we implement the web components had to be modified to deliver the site the way I thought it was.

Now it should be:
Safari 9.1 / IE 11 / lower -- frame based site
Edge -- watered down design (from picture above)
Firefox 52-67/Seamonkeys/Safari 10.1 -- ES6 with AMD compiling
Evergreen (all) -- Native ES6

Going to reflect this in our docs.

**Comment by joyously** [comment]
Yes, it does look different now.
![HAX-the-web-0324](https://user-images.githubusercontent.com/7957680/62910041-abd80e80-bd44-11e9-99d9-5222c3dc8de0.jpg)
