### ISSUE TITLE
clean up sentence

### ISSUE THREAD

**Issue by btopro** [elmsln/haxtheweb.org#10]
from #3
`Elements created by HAX can work anywhere with or without HAXHAX can be extended to understand how to modify just about any element`

should be changed to

HAX can be extended to understand how to modify just about any custom element!

https://github.com/elmsln/haxtheweb.org/blob/master/pages/what-is-it/index.html

**Comment by tomsshow** [comment]
The proposed change seems to already have been made:
![image](https://user-images.githubusercontent.com/14881497/64370832-3e3e9b80-cfed-11e9-9e56-1dae0fdd237b.png)

I think this issue can be closed now
