### ISSUE TITLE
recursive url broken link

### ISSUE THREAD

**Issue by tomsshow** [elmsln/haxtheweb.org#17]
going to haxtheweb.org/ux-concepts gets you the image below. It will continuously tries to add `/~and~q=p/` to the url
![image](https://user-images.githubusercontent.com/14881497/66618686-0e645400-eba8-11e9-9da5-328f36e86dcc.png)

**Comment by btopro** [comment]
no that would appear to be any link if it's not hit after already having the top level....hmmm
