### ISSUE TITLE
ordering of pages

### ISSUE THREAD

**Issue by joyously** [elmsln/haxtheweb.org#4]
I was trying to go through the pages in order, but they don't make sense in the order they are in.
I thought I would copy the text from the menu on the site, but it won't let me. I assume it's because it's a web component. That's not very user-friendly. (And every time I click on Principles in the menu, it is slow to load, then once loaded, it scrolls all the way down to the bottom of the menu.)

Welcome
- What is HAX
- Why HAXcms
- Principles
- Roadmap
- Try hax
- Presentations
- I have issues

It looks to me like `Principles` should be part of `Why HAXcns`.
It looks like `Roadmap` should come before `Why HAXcms`, but it also looks like the whole `Solutions` section should come before the `Roadmap`.

Somewhere in here should be a mention of how the javascript for the web components gets loaded when the content is sent to the browser. Other pages say that HAX is not needed, so how does that happen?
Also, something should be said about where the web components are stored.

------------------
The `Try hax` (HAX?) page says that the website is a demo of HAX, and to `click the bottom right and get this party started playing with all the capabilities HAX has to offer!` 
There is nothing to click in the bottom right.
The entire paragraph is shown twice.
![try-hax-page](https://user-images.githubusercontent.com/7957680/62845298-7ff95200-bc8c-11e9-8ddd-74ceb1c239cb.jpg)

The `Presentations` page says there is a playlist, but it looks like a single video.

**Comment by btopro** [comment]
Thank you for this, it's all excellent feedback and well targeted. I've just pushed up a new update to the site that addresses all of these issues in docs.
