### ISSUE TITLE
menu arrows

### ISSUE THREAD

**Issue by joyously** [elmsln/haxtheweb.org#7]
There are so many different UIs on computers and the web, but menu arrows are fairly standardized.
Typically, the arrow is an interactive element and not a state indicator, as the majority of menus are dropdowns. When the menu is an accordion, the arrow often is just an indicator of the state of the menu.
The menu on this site uses the arrow for both interaction and state, and it is confusing. Since it is for interaction, it makes sense that it show what will happen on click (point down when closed, point up when open). But to show state, it is pointing up when closed and pointing down when open.
I have programs that use a different arrow to show state, but arrow for interaction is the standard one being used here.

So the confusion is: should the menu arrow be the standard arrow for interaction if it is used for state?

One other thing is that the same size arrow is used for a narrow window, which would be clicked with a finger (not as precise as a mouse).

**Comment by btopro** [comment]
Selecting the link that it is associated with should open the dropdown at the same time. The arrow then serves as this indicator. The arrow can be clicked to re-collapse or open without going to a page. I'm not saying this is correct behavior just how functions currently. cc @heyMP

**Comment by joyously** [comment]
Right, it's a combination of interactive and state, which is confusing since the direction of the pointer is for state, but it is still interactive. It just seems backwards to all the other arrows I encounter.

**Comment by btopro** [comment]
next build has this incorporated
